Update GH actions
metno/pyaerocom pull request #1040
Opened 2024-03-13 11:12 UTC by avaldebe

avoid CI warnings like
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20
```

2024-03-13 11:25 UTC, heikoklein commented
I still see the same warnings in the test-actions: https://github.com/metno/pyaerocom/actions/runs/8263687888

And (maybe not relevant) why is 3.9 still tested here?

2024-03-13 13:07 UTC, heikoklein requested changes
https://github.com/metno/pyaerocom/actions/runs/8263687888 still shows same warnings as before: 
venv (3.11, false, ubuntu-22.04)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

2024-03-13 18:44 UTC, heikoklein requested changes
The conda-test warns still about node16 (the others are fine now). I see `codecov/codecov-action@v4` is out. Maybe you can give that a try?

2024-03-14 09:00 UTC, heikoklein requested changes
Something wrong with codecov now:
```
conda (3.10, false)
Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

2024-03-18 11:17 UTC, heikoklein commented
codecov action fails because tokenless uploads are no longer supported, i.e. missing:
```
token: ${{ secrets.CODECOV_TOKEN }} # required
```
see https://github.com/codecov/codecov-action?tab=readme-ov-file#breaking-changes

2024-03-18 13:57 UTC, avaldebe commented
> codecov action fails because tokenless uploads are no longer supported, i.e. missing:
> 
> ```
> token: ${{ secrets.CODECOV_TOKEN }} # required
> ```
> 
> see https://github.com/codecov/codecov-action?tab=readme-ov-file#breaking-changes

fixed

2024-03-18 15:52 UTC, heikoklein approved these changes

2024-03-18 15:53 UTC, merged