clean up deprecations
metno/pyaerocom pull request #1070
Opened 2024-03-20 10:53 UTC by avaldebe

## Change Summary

- update `pytests` configuration so `DeprecationWarnings` and are ingored, instead of trated as errors
- remove deprecated `pyaerocom` classes and class methods, so there is no need to test against its usage on `pyaerocom` sub modules

## Related issue number

closes #1065 and #1066

## Checklist

* [X] Start with a draft-PR
* [X] The pull request title is a good summary of the changes
* [X] Documentation reflects the changes where applicable
* [X] Tests for the changes exist where applicable
* [X] Tests pass first locally and then on CI
* [ ] My PR is ready to review and I have selected a reviewer

## Note to reviewers

@dulte @jgriesfeller @lewisblake @heikoklein 

Please check that the deprecated code is not used on one of your PRs and `pyerocom` related projects.
Only merge this PR after all reviewers approve.

2024-03-20 11:39 UTC, heikoklein requested changes
Removing deprecated methods in pyaerocom has not been planned or decided upon. I leave it to @lewisblake to make a decision if and when to remove deprecated methods. It should be removed from this PR.

Issue #1065 is addressed by the change in pyproject.toml I think.
Issue #1066 should *not* be closed by this PR. It is a companion issue to be taken up every 2 month to check if new warnings appear in the tests, so it was planned for m2024-06 (and should open a new one for m2024-08 and so on...)

2024-03-20 12:47 UTC, lewisblake commented
Maybe the portion of the PR which addresses #1065 should be handled first. In general, I am okay with removing deprecated pyaerocom code. That said I think it may be preferable to handle that as a separate PR.

2024-03-21 09:03 UTC, avaldebe commented
OK, I'll remove the deprecation removal and focus on #1065

2024-03-21 14:51 UTC, heikoklein approved these changes

2024-03-21 15:04 UTC, merged