small improvement to tests
metno/pyaerocom pull request #1136
Opened 2024-04-24 11:18 UTC by charlienegri

## Change Summary
small tweaks to tests to better represent the code after #1128 was merged

## Checklist

* [ ] Start with a draft-PR
* [x ] The PR title is a good summary of the changes
* [ ] PR is set to AeroTools and a tentative milestone
* [ ] Documentation reflects the changes where applicable
* [ ] Tests for the changes exist where applicable
* [x ] Tests pass locally
* [ ] Tests pass on CI
* [ x] At least 1 reviewer is selected
* [ ] Make PR ready to review

2024-04-24 15:11 UTC, charlienegri commented
maybe I should add a test for _check_statistics_periods too

2024-04-25 07:30 UTC, lewisblake requested changes
Merge main-dev into this to get rid off the hoqq file first, but otherwise it looks good. Thanks for these improved tests!

2024-04-25 07:30 UTC, lewisblake commented on hoqq
This file is no longer in main-dev. please merge from main-dev.

2024-04-25 07:58 UTC, charlienegri commented on hoqq
rebased thanks to Magnus' advice

2024-04-25 07:58 UTC, lewisblake approved these changes
:rocket:

2024-04-25 07:58 UTC, merged