Merge trends-fix into main-dev
metno/pyaerocom pull request #1266
Opened 2024-07-15 13:59 UTC by dulte

## Change Summary
Branch for merging main-dev into trends-fix branch

## Related issue number

fix #903

## Checklist

* [ x] Start with a draft-PR
* [ x] The PR title is a good summary of the changes
* [ x] PR is set to AeroTools and a tentative milestone
* [ ] Documentation reflects the changes where applicable
* [ ] Tests for the changes exist where applicable
* [ ] Tests pass locally
* [ ] Tests pass on CI
* [x ] At least 1 reviewer is selected
* [ ] Make PR ready to review

2024-07-17 13:04 UTC, dulte commented on pyaerocom/trends_helpers.py
> +
This is a new addition which I'm not sure was added, but which makes sense. I need to look at this

2024-07-18 11:47 UTC, heikoklein requested changes
A typo found. And test fail:
```            assert "trends_min_yrs" not in cfg_exp1
>           assert statistics_opts.trends_min_yrs == 7
E           assert 0 == 7
E            +  where 0 = StatisticsSetup(MIN_NUM=1, weighted_stats=True, annual_stats_constrained=True, add_trends=False, avg_over_trends=False...l=False, obs_only_stats=False, model_only_stats=False, drop_stats=(), stats_decimals=None, round_floats_precision=None).trends_min_yrs
```

2024-07-18 11:47 UTC, heikoklein commented on pyaerocom/aeroval/setupclasses.py
> +    min_yrs: PositiveInt = 0                        # Removes stations with less that this number of years of valid data (a year with data points in all four seasons) Should in most cases be the same
typo: less tha*n* this

2024-07-18 14:26 UTC, heikoklein approved these changes

2024-07-18 14:27 UTC, merged