[ReadMscwCtm] Supporting selecting files to be read by regexp match
metno/pyaerocom pull request #1423
Opened 2024-11-25 12:05 UTC by thorbjoernl

## Change Summary

Support providing a custom regular expression to the EMEP reader which can be used to select files instead of the 'Base_{freq}.nc' matching that is currently being used.

## Related issue number

#1175 

## Checklist

* [ ] Start with a draft-PR
* [ ] The PR title is a good summary of the changes
* [ ] PR is set to AeroTools and a tentative milestone
* [ ] Documentation reflects the changes where applicable
* [ ] Tests for the changes exist where applicable
* [ ] Tests pass locally
* [ ] Tests pass on CI
* [ ] At least 1 reviewer is selected
* [ ] Make PR ready to review

2024-11-26 08:56 UTC, heikoklein requested changes

2024-11-26 08:56 UTC, heikoklein commented on pyaerocom/io/mscw_ctm/reader.py
> +        if (pattern := kwargs.get("file_pattern", None)) is None:
overuse of wallruss operator

2024-11-26 08:56 UTC, heikoklein commented on pyaerocom/io/mscw_ctm/reader.py
> +                f"Provided pattern '{pattern}' of type {type(pattern)} can't be compiled to re.Pattern. Please provide str or re.Pattern."
The user only knows `file_pattern`, not `pattern`. And you haven't tried to compile yet, did you?

2024-11-26 08:56 UTC, heikoklein commented on pyaerocom/io/mscw_ctm/reader.py
> +    def __init__(self, data_id: str | None = None, data_dir: str | None = None, **kwargs):
documentation of file_pattern missing. Why not raise it to usual parameters and hide it in kwargs?

2024-11-26 08:56 UTC, heikoklein commented on pyaerocom/io/mscw_ctm/reader.py
> +                if self._private.file_pattern is not None:
how can that be None? It must be set in init.

2024-12-02 10:08 UTC, thorbjoernl commented
Closing because changes are merged with #1425

2024-12-02 10:08 UTC, closed without merging