Hans main dev
metno/pyaerocom pull request #344
Opened 2021-03-11 08:41 UTC by hansbrenna

Really just to check what I've changed

2021-03-26 11:41 UTC, hansbrenna commented
@jgliss I don't understand why the test_varinfo test fails for conctc. Can you help?

2021-03-30 11:12 UTC, jgliss requested changes
@hansbrenna I went through it mostly looks good, however, there are a few things that we need to clarify / fix before merging. The most pressing issue is probably the molmass of nh3, which might be wrong. And also the units related issues, where I would appreciate if you could make adjustments in variable names and / or units, if possible. Best if you comment on my individual comments and we take it from there.

2021-03-30 11:12 UTC, jgliss commented on pyaerocom/web/aerocom_evaluation.py
> +                                    match = False
Could you add a test that reaches this code (i.e. handling of model_add_vars as list)?

2021-03-31 08:30 UTC, jgliss commented on pyaerocom/molmasses.py
> +             'nh3'      : 43.028,
```suggestion
             'nh3'      : 17.031,
```

2021-03-31 09:45 UTC, jgliss commented
@hansbrenna thanks for the meeting! As discussed, maybe we can use the following variable conventions to distinguish the units:

`concno3` -> ug m-3
`concNno3` -> ug N m-3

And for variable names representing a certain PM size regime, we add pmX at the end, e.g. 

`concno3pm10`
`concno3pm25`

Just let me know when you are ready with the updates so I can revise

2021-03-31 11:21 UTC, hansbrenna commented on pyaerocom/data/variables.ini
> +
removing this.

2021-03-31 12:04 UTC, jgliss requested changes
Looks good! Just some minor re-iteration needed for variable defs. Seems also that the EBAS test PROVIDES_VARIABLES has some old variables in it (e.g. concec, concec25). Should be quick to fix for you.

2021-03-31 12:04 UTC, jgliss commented on pyaerocom/io/test/test_read_ebas.py
> +                         'concss10',
```suggestion
                         'concsspm10',
```

2021-03-31 12:04 UTC, jgliss commented on pyaerocom/io/test/test_read_ebas.py
> +                         'concss25',
```suggestion
                         'concsspm25',
```

2021-04-06 08:34 UTC, hansbrenna commented
I've done the updates suggested. Waiting for the checks to run.

2021-04-06 09:55 UTC, hansbrenna commented
Should we merge this now @jgliss ?

2021-04-06 10:01 UTC, jgliss approved these changes
Looks good now :)

2021-04-06 10:02 UTC, merged