Seasalt
metno/pyaerocom pull request #460
Opened 2021-09-30 09:05 UTC by dulte

Sea salt pm 25, and more

2021-09-30 09:15 UTC, jgliss commented
@dulte can you check the failing tests first and make sure CI passes?

2021-09-30 09:31 UTC, dulte commented
It was the test function that wasn't updated with the new definition of sea salt. This is fixed now

2021-09-30 09:42 UTC, jgliss commented
@dulte we just merged  #410 into main-dev, could you add the updates to this branch before we merge?

2021-09-30 09:46 UTC, dulte commented
Pulled the newest updates from main-dev and pushed it to this branch

2021-09-30 10:46 UTC, jgliss approved these changes
Looks good (but you might need to add concssf in variables.ini, not sure if it exists)

2021-09-30 10:46 UTC, jgliss commented on pyaerocom/data/emep_variables.ini
> +concssf=SURF_ug_SEASALT_F
I guess this is still concsspm25 in ebas_config.ini. Also you probably need to add the new variable concssf in variables.ini.

2021-09-30 10:46 UTC, jgliss commented on pyaerocom/io/read_mscw_ctm.py
> +    concsspm25 = concssf + coarse_fraction*concssc
Ah, then co-location works if you use concsspm25!

2021-09-30 10:47 UTC, jgliss requested changes
Actually, cleanup of glob_defaults needed before approval, sorry for the confusion.

2021-09-30 10:55 UTC, dulte commented
I think most of the duplicates from glob default should be gone now

2021-09-30 11:02 UTC, jgliss reviewed
Perhaps you could add a test module for glob_defaults in tests/aeroval and add a test to make sure there no duplicates. Not important to do that now, but I think this should be tested before we merge.

2021-10-01 06:49 UTC, dulte commented
Dicts made with {} will only keep the last duplicate entry, so that as soon as var_web_info actually becomes a dict in python, there will be no duplicates, meaning that we can test for it. If we change {} to dict(), it will crash instead, which might be better

2021-10-01 07:23 UTC, jgliss commented
> Dicts made with {} will only keep the last duplicate entry, so that as soon as var_web_info actually becomes a dict in python, there will be no duplicates, meaning that we can test for it. If we change {} to dict(), it will crash instead, which might be better

Sounds good!

2021-10-04 07:34 UTC, jgliss approved these changes
Looks good

2021-10-04 09:06 UTC, merged