Adds list of regions instead of just the best
metno/pyaerocom pull request #582
Opened 2022-02-07 12:46 UTC by dulte

Addressing #580

2022-02-08 08:24 UTC, avaldebe reviewed
I have a couple of suggestions in order to improve the maintainability following up.

2022-02-08 08:24 UTC, avaldebe commented on pyaerocom/region.py
> +        return matches[0], matches
You're changing the type of the return from `str` to `tuple[str, list[str]]`.
I would create a new data structure for the result. Something based on `typing.NamedTuple`, like this:

``` python
from __future__ import annotations
[...]
from typing import NamedTuple
[...]

class ClosestRegion(NamedTuple):
    best: str
    matches: list[str]

def find_closest_region_coord(
    lat: float,
    lon: float,
    regions: dict[str, Region] | None = None
) -> ClosestRegion:
    [...]
    return ClosestRegion(best, matches)
```

This way you get attribute access to the `find_closest_region_coord` resuts, e.g.

``` python
reg = find_closest_region_coord(lon, lat, regions=regions)
# closest region ID
reg.best
# all regions applicable
reg.matches 
```

2022-02-08 08:24 UTC, avaldebe commented on pyaerocom/region.py
>      min_dist = 1e6
this part could be replaced by

``` python
matches.sort(key=lambda id: regions[id].distance_to_center(lat, lon))
return ClosestRegion(matches[0], matches)
```

2022-02-08 08:27 UTC, avaldebe commented on pyaerocom/aeroval/coldatatojson_helpers.py
>      return regs
or using the data structure introduced on my next comment

``` python
def _get_stat_regions(
    lats: list[float], 
    lons: list[float],
    regions: dict[str, Region] | None,
) -> list[ClosestRegion]:
    assert len(lats) == len(lons), "miss match number of lat/lon"
    return [
        find_closest_region_coord(lat, lon, regions=regions)
        for lat, lon in zip(lats, lons)
    ]
```

2022-05-05 13:49 UTC, avaldebe requested changes
small changes, mostly cleaning up commented code

2022-05-05 13:49 UTC, avaldebe commented on pyaerocom/region.py
> +) -> List[str]:
here you could use the `|` style of annotations, introduced on Python 3.10:

``` python
from __future__ import annotations # the very first import
...
def find_closest_region_coord(
    lat: float,
    lon: float,
    regions: dict | None = None,
) -> list[str]:
    ...
```

2022-05-05 13:49 UTC, avaldebe commented on pyaerocom/region.py
> +    #         best = match
please remove dead code

2022-05-12 11:51 UTC, merged

2022-06-07 09:18 UTC, AugustinMortier commented
I believe this is connected to this issue, but it appears that some regions are never returned in the list of regions, such as 'N America': e.g: [AeronetL1.5-d-od550aer_Column_IFS-CTRL-od550aer.json](https://gitlab.met.no/aeroval/cams2-82/-/raw/master/IFS/map/AeronetL1.5-d-od550aer_Column_IFS-CTRL-od550aer.json)

As a result, the minimap is not highlighting any station in the selected region in the mini map.
![Screenshot from 2022-06-07 11-14-56](https://user-images.githubusercontent.com/19610522/172343806-6f04ff90-8ea1-448a-b19d-23050907c1b4.png)

Other regions also affected by this issue are:
- Rus,Bel,Ukr
- Pacific,Aust,NZ,

My suspicion is that those regions are probably crossing the -180/180 degrees longitude and that is maybe not well taken into account when fetching the closest region.

2022-06-07 09:30 UTC, AugustinMortier commented
In addition, it seems that the 'Oceans' region is added to almost all of the stations. This is not affecteing the statistics calculation though, as the number of stations shown in each region seems to be correct. So we should make sure that the regions in the region list is consistent with the regions used in the statistics calculation.

e.g: AERONET: 
- WORLD: 300 stations
- Oceans: 30 stations

![Screenshot from 2022-06-07 11-27-49](https://user-images.githubusercontent.com/19610522/172346626-44174fac-7d1e-4985-b0d0-476bedd72ab0.png)

![Screenshot from 2022-06-07 11-28-15](https://user-images.githubusercontent.com/19610522/172346654-99aca64d-a61e-4047-a994-c36919cf5c69.png)